name: Flatpak-devel

on:
# Every Sundays at 00:00:00 GMT
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  APP_ID: io.github.nijigenerate.nijigenerate
  MANIFEST_PATH: build-aux/linux/flatpak/nightly/io.github.nijigenerate.nijigenerate.yml
  FLATPAK_BUNDLE: nijigenerate
  FLATPAK_BRANCH: nightly
  FLATPAK_BUILD_REPO: build-repo
  FLATPAK_BUILD_DIR: build-dir

permissions:
  contents: write

jobs:
  build-flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Dump canonical manifest
      run: |
        set -e
        flatpak-builder --show-manifest ${MANIFEST_PATH} > canonical-manifest.json

    - name: Download flatpak SDK and sources
      run: |
        set -e
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --install-deps-from=flathub --install-deps-only --user /dev/null ${MANIFEST_PATH}
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --download-only /dev/null ${MANIFEST_PATH}

    - name: Prime cache
      uses: actions/cache@v4
      with:
        path: |
          .flatpak-builder/ccache
        key: flatpak-builder-${{ hashFiles('canonical-manifest.json') }}
        restore-keys: |
          flatpak-builder-

    - name: Build flatpak
      run: |
        set -e
        flatpak-builder --default-branch=${FLATPAK_BRANCH} --ccache --repo=${FLATPAK_BUILD_REPO} ${FLATPAK_BUILD_DIR} ${MANIFEST_PATH}

    - name: Upload flatpak repo
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FLATPAK_BUILD_REPO }}
        path: |
          ${{ env.FLATPAK_BUILD_REPO }}
          !${{ env.FLATPAK_BUILD_REPO }}/.lock

  publish-flatpak-bundle:
    runs-on: ubuntu-latest
    needs: build-flatpak

    steps:
    - uses: actions/checkout@v4

    - name: Install flatpak
      run: |
        set -e
        sudo apt update
        sudo apt install -y flatpak

    - name: Download flatpak repo
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.FLATPAK_BUILD_REPO }}
        path: ${{ env.FLATPAK_BUILD_REPO }}

    - name: Create flatpak bundle
      run: |
        set -e
        mkdir -p ${FLATPAK_BUILD_REPO}/{extensions,refs/{mirrors,remotes},state,tmp/cache}
        flatpak build-bundle --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo ${FLATPAK_BUILD_REPO} ${FLATPAK_BUNDLE}.flatpak ${APP_ID} ${FLATPAK_BRANCH}
        flatpak build-bundle --runtime ${FLATPAK_BUILD_REPO} ${FLATPAK_BUNDLE}.debug.flatpak ${APP_ID/-/_}.Debug ${FLATPAK_BRANCH}

    - name: Release to nightly tag
      uses: softprops/action-gh-release@v1
      with:
        name: 'Nightly Build'
        tag_name: nightly
        files: |
          ${{ env.FLATPAK_BUNDLE }}.flatpak
          ${{ env.FLATPAK_BUNDLE }}.debug.flatpak

