# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Pull Request test

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7
      with:
        compiler: ldc-latest

    - name: "Get build dependencies"
      run: |
        sudo apt-get update
        sudo apt install libsdl2-dev libfreetype6-dev gettext

    - name: 'Generate i18n'
      run: |
        sudo chmod +x ./gentl.sh
        ./gentl.sh
      
    - name: "Clone dependencies & set versions"
      run: |
        git clone https://github.com/inochi2d/i2d-imgui.git --recurse-submodules
        git clone https://github.com/nijigenerate/nijilive.git
        dub add-local i2d-imgui/ "0.8.0"
        dub add-local nijilive/ "0.0.1"
        cd i2d-imgui
        git checkout c6a78f4a7510fd31a86998b7ceedfc2916ecfae0
        git submodule update --recursive

    - name: 'Build and Test'
      run: |
        # Build metadata (like version information and icons)
        dub build --config=meta
        
        # Build the project, with its main file included, without unittests
        dub build --compiler=ldc2 --build=release --config=linux-full

    - name: "Upload Artifacts"  
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: nijigenerate
        path: out/nijigenerate
